"""update schema toan bo, them ngay day range

Revision ID: 401947e063f6
Revises: 8ab313b0d5a8
Create Date: 2026-03-25 23:22:24.649728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '401947e063f6'
down_revision: Union[str, None] = '8ab313b0d5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teaching_sessions')
    op.drop_table('uploaded_files')
    op.drop_table('session_date_ranges')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_date_ranges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ngay_bat_dau', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ngay_ket_thuc', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['teaching_sessions.id'], name='session_date_ranges_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='session_date_ranges_pkey')
    )
    op.create_table('uploaded_files',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('uploaded_files_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('truong', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hoc_ky', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='uploaded_files_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('teaching_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ma_mon', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ten_mon', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lop', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('si_so', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thu', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('tiet_bat_dau', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('tiet_ket_thuc', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('so_tiet', sa.SMALLINT(), sa.Computed('((tiet_ket_thuc - tiet_bat_dau) + 1)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('phong', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('truong', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hoc_ky', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.id'], name='teaching_sessions_source_file_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='teaching_sessions_pkey')
    )
    # ### end Alembic commands ###
